const CartTypes = {
  TOGGLE_CART_PREVIEW: "TOGGLE_CART_PREVIEW",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
};

export default CartTypes;
