const CatalogTypes = {
  LOAD_COLLECTIONS_START: "LOAD_COLLECTIONS_START",
  LOAD_COLLECTIONS_SUCCESS: "LOAD_COLLECTIONS_SUCCESS",
  LOAD_COLLECTIONS_FAIL: "LOAD_COLLECTIONS_FAIL",
};

export default CatalogTypes;
