const UserActionTypes = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_IN_WITH_EMAIL_AND_PASSWORD_START:
    "SIGN_IN_WITH_EMAIL_AND_PASSWORD_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  CHECK_SIGN_IN: "CHECK_SIGN_IN",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
};

export default UserActionTypes;
